import { writeFile, mkdir, readFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

// Two backends, same interface. Local disk is what actually runs and is
// tested today; S3 is wired up and will activate the moment S3_* env vars
// are set, with no code changes — same dev/prod-fallback pattern as
// lib/email.ts and lib/rateLimit.ts.
//
// An upload can arrive two ways. Small files are proxied through this
// server as multipart. With S3 configured, large ones are uploaded
// straight from the browser to a pre-signed URL, so a 200MB video never
// occupies this server's memory.
//
// Both end up in the same place: lib/mediaPipeline.ts validates,
// re-encodes and scans the bytes before anything reaches a servable key.
// A direct upload lands under QUARANTINE_PREFIX, which the bucket policy
// must NOT make public — see docs/deployment.md — and is deleted once it
// has been processed.
const LOCAL_DIR = join(process.cwd(), ".local-uploads");

/**
 * Where a browser's direct upload lands, before anything has looked at it.
 *
 * Separate from the servable keys so a bucket policy can make one public
 * and not the other. Objects here are unvalidated and unscanned: treat the
 * prefix as hostile.
 */
export const QUARANTINE_PREFIX = "quarantine/";

/** How long a browser has to use an upload URL before it stops working. */
const UPLOAD_URL_TTL_SECONDS = 15 * 60;

const s3Configured = !!(
  process.env.S3_ENDPOINT &&
  process.env.S3_BUCKET &&
  process.env.S3_ACCESS_KEY_ID &&
  process.env.S3_SECRET_ACCESS_KEY
);

let s3Client: S3Client | null = null;
function getS3(): S3Client {
  if (!s3Client) {
    s3Client = new S3Client({
      endpoint: process.env.S3_ENDPOINT,
      region: process.env.S3_REGION || "auto",
      credentials: {
        accessKeyId: process.env.S3_ACCESS_KEY_ID!,
        secretAccessKey: process.env.S3_SECRET_ACCESS_KEY!,
      },
    });
  }
  return s3Client;
}

export function isS3Configured(): boolean {
  return s3Configured;
}

export interface StoredObject {
  storageKey: string;
  url: string;
}

export async function storeObject(
  buffer: Buffer,
  contentType: string,
  extension: string
): Promise<StoredObject> {
  const storageKey = `${randomUUID()}.${extension}`;

  if (s3Configured) {
    await getS3().send(
      new PutObjectCommand({
        Bucket: process.env.S3_BUCKET!,
        Key: storageKey,
        Body: buffer,
        ContentType: contentType,
      })
    );
    // Deliberately not a signed/expiring URL: media is only served once its
    // Media row is scanStatus = CLEAN, and production should put a CDN in
    // front of the bucket on a cookie-less domain — see security blueprint.
    //
    // `||` rather than `??` on purpose: MEDIA_PUBLIC_BASE_URL ships as an
    // empty string in .env.example, and an empty string is not nullish —
    // `??` would happily build "/key" URLs that 404 in production.
    const base = (process.env.MEDIA_PUBLIC_BASE_URL || process.env.S3_ENDPOINT || "").replace(/\/$/, "");
    return { storageKey, url: `${base}/${storageKey}` };
  }

  if (!existsSync(LOCAL_DIR)) await mkdir(LOCAL_DIR, { recursive: true });
  await writeFile(join(LOCAL_DIR, storageKey), buffer);
  return { storageKey, url: `/media/${storageKey}` };
}

/** Local-disk only — the S3 path serves directly from the bucket/CDN URL instead. */
export async function readLocalObject(storageKey: string): Promise<Buffer> {
  assertSafeStorageKey(storageKey);
  return readFile(join(LOCAL_DIR, storageKey));
}

/**
 * storageKey is generated by us (randomUUID + extension) and never taken
 * from user input directly, but the local media route handler passes a
 * URL path segment straight through to this function — reject anything
 * that isn't the shape we generate before it ever reaches the filesystem.
 */
function assertSafeStorageKey(storageKey: string): void {
  if (!/^[a-f0-9-]+\.[a-z0-9]+$/i.test(storageKey)) {
    throw new Error("Invalid storage key");
  }
}

export interface PresignedUpload {
  uploadUrl: string;
  storageKey: string;
  expiresInSeconds: number;
}

/**
 * A URL the browser can PUT bytes to directly.
 *
 * Only possible with S3 configured; there is nothing to pre-sign on local
 * disk, so callers fall back to proxying the upload through this server.
 *
 * The signature commits to the key and the method, but not to the content:
 * whatever arrives is unvalidated, which is exactly why it lands in
 * quarantine and is processed before anything can serve it.
 */
export async function presignUpload(extension: string): Promise<PresignedUpload | null> {
  if (!s3Configured) return null;

  const storageKey = `${QUARANTINE_PREFIX}${randomUUID()}.${extension}`;
  const uploadUrl = await getSignedUrl(
    getS3(),
    new PutObjectCommand({ Bucket: process.env.S3_BUCKET!, Key: storageKey }),
    { expiresIn: UPLOAD_URL_TTL_SECONDS }
  );

  return { uploadUrl, storageKey, expiresInSeconds: UPLOAD_URL_TTL_SECONDS };
}

/** Reads an object back, to validate and re-encode what a browser uploaded. */
export async function readObject(storageKey: string): Promise<Buffer> {
  if (!s3Configured) {
    assertSafeStorageKey(storageKey);
    return readFile(join(LOCAL_DIR, storageKey));
  }

  const response = await getS3().send(
    new GetObjectCommand({ Bucket: process.env.S3_BUCKET!, Key: storageKey })
  );
  const bytes = await response.Body?.transformToByteArray();
  if (!bytes) throw new Error("empty object");
  return Buffer.from(bytes);
}

/**
 * Removes an object. Used to clear quarantine once a file has been
 * processed — or rejected, which is when it matters most: unscanned bytes
 * must not accumulate in a bucket.
 */
export async function deleteObject(storageKey: string): Promise<void> {
  if (!s3Configured) {
    assertSafeStorageKey(storageKey);
    await rm(join(LOCAL_DIR, storageKey), { force: true });
    return;
  }

  await getS3().send(
    new DeleteObjectCommand({ Bucket: process.env.S3_BUCKET!, Key: storageKey })
  );
}

/**
 * True for a key this module issued for a direct upload.
 *
 * Finalising takes a key from the client, so it must be one we handed out:
 * the quarantine prefix plus the UUID-and-extension shape, and nothing
 * that could climb out of it.
 */
export function isQuarantineKey(storageKey: string): boolean {
  if (!storageKey.startsWith(QUARANTINE_PREFIX)) return false;
  const name = storageKey.slice(QUARANTINE_PREFIX.length);
  return /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\.[a-z0-9]{1,8}$/i.test(name);
}
