import { writeFile, mkdir, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

// Two backends, same interface. Local disk is what actually runs and is
// tested today; S3 is wired up and will activate the moment S3_* env vars
// are set, with no code changes — same dev/prod-fallback pattern as
// lib/email.ts and lib/rateLimit.ts.
//
// Both paths proxy the upload through our own server rather than doing a
// true direct-to-S3 presigned upload (client -> S3, bypassing the app
// server for the bytes). That's a deliberate simplification: a true
// direct upload defers validation to a post-upload hook (an S3 event
// trigger + Lambda, in the plan's original design) that needs
// infrastructure this project doesn't have provisioned. Proxying through
// the server means the exact same validate → re-encode → checksum
// pipeline (see the upload route handler) runs inline for both local disk
// and S3, so the safety guarantees are identical either way. Revisit if
// large video uploads make the proxy path a bottleneck.
const LOCAL_DIR = join(process.cwd(), ".local-uploads");

const s3Configured = !!(
  process.env.S3_ENDPOINT &&
  process.env.S3_BUCKET &&
  process.env.S3_ACCESS_KEY_ID &&
  process.env.S3_SECRET_ACCESS_KEY
);

let s3Client: S3Client | null = null;
function getS3(): S3Client {
  if (!s3Client) {
    s3Client = new S3Client({
      endpoint: process.env.S3_ENDPOINT,
      region: process.env.S3_REGION || "auto",
      credentials: {
        accessKeyId: process.env.S3_ACCESS_KEY_ID!,
        secretAccessKey: process.env.S3_SECRET_ACCESS_KEY!,
      },
    });
  }
  return s3Client;
}

export function isS3Configured(): boolean {
  return s3Configured;
}

export interface StoredObject {
  storageKey: string;
  url: string;
}

export async function storeObject(
  buffer: Buffer,
  contentType: string,
  extension: string
): Promise<StoredObject> {
  const storageKey = `${randomUUID()}.${extension}`;

  if (s3Configured) {
    await getS3().send(
      new PutObjectCommand({
        Bucket: process.env.S3_BUCKET!,
        Key: storageKey,
        Body: buffer,
        ContentType: contentType,
      })
    );
    // Deliberately not a signed/expiring URL: media is only served once its
    // Media row is scanStatus = CLEAN, and production should put a CDN in
    // front of the bucket on a cookie-less domain — see security blueprint.
    //
    // `||` rather than `??` on purpose: MEDIA_PUBLIC_BASE_URL ships as an
    // empty string in .env.example, and an empty string is not nullish —
    // `??` would happily build "/key" URLs that 404 in production.
    const base = (process.env.MEDIA_PUBLIC_BASE_URL || process.env.S3_ENDPOINT || "").replace(/\/$/, "");
    return { storageKey, url: `${base}/${storageKey}` };
  }

  if (!existsSync(LOCAL_DIR)) await mkdir(LOCAL_DIR, { recursive: true });
  await writeFile(join(LOCAL_DIR, storageKey), buffer);
  return { storageKey, url: `/media/${storageKey}` };
}

/** Local-disk only — the S3 path serves directly from the bucket/CDN URL instead. */
export async function readLocalObject(storageKey: string): Promise<Buffer> {
  assertSafeStorageKey(storageKey);
  return readFile(join(LOCAL_DIR, storageKey));
}

/**
 * storageKey is generated by us (randomUUID + extension) and never taken
 * from user input directly, but the local media route handler passes a
 * URL path segment straight through to this function — reject anything
 * that isn't the shape we generate before it ever reaches the filesystem.
 */
function assertSafeStorageKey(storageKey: string): void {
  if (!/^[a-f0-9-]+\.[a-z0-9]+$/i.test(storageKey)) {
    throw new Error("Invalid storage key");
  }
}
