-- AlterTable
ALTER TABLE `Media` ADD COLUMN `caption` TEXT NULL,
    ADD COLUMN `credit` VARCHAR(191) NULL,
    ADD COLUMN `license` ENUM('OWN_WORK', 'PERMISSION', 'CC0', 'CC_BY', 'CC_BY_SA', 'CC_BY_ND', 'CC_BY_NC', 'CC_BY_NC_SA', 'CC_BY_NC_ND', 'PUBLIC_DOMAIN', 'OTHER') NULL,
    ADD COLUMN `rightsConfirmedAt` DATETIME(3) NULL,
    ADD COLUMN `rightsNote` TEXT NULL,
    ADD COLUMN `sizeBytes` INTEGER NULL,
    ADD COLUMN `sourceName` VARCHAR(191) NULL,
    ADD COLUMN `sourceUrl` VARCHAR(2000) NULL,
    ADD COLUMN `title` VARCHAR(191) NULL,
    ADD COLUMN `transcript` TEXT NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `type` ENUM('IMAGE', 'VIDEO', 'AUDIO') NOT NULL;

