import type { Metadata, Viewport } from "next";
import { Fraunces, Inter, Source_Serif_4 } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { SITE_DESCRIPTION, SITE_NAME, siteUrl } from "@/lib/siteUrl";
import { I18nProvider } from "@/i18n/client";
import { LOCALE_DIR } from "@/i18n/config";
import { MESSAGES } from "@/i18n/messages";
import { getI18n, getLocale } from "@/i18n/server";
import { getTheme } from "@/theme/server";
import { THEME_COLOR, themeAttribute } from "@/theme/config";

// Three faces, three jobs. Inter for the interface and its numbers;
// Source Serif 4 for reading, at optical sizes tuned for 19px; Fraunces
// for headlines, where its optical axis goes from crisp at card size to
// expressive at the front page's lead. All self-hosted at build time.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
  style: ["normal", "italic"],
  axes: ["opsz"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  style: ["normal", "italic"],
  axes: ["opsz"],
});

/**
 * Every page renders per request.
 *
 * Not a performance choice — a prerequisite for the Content-Security-
 * Policy. Next.js injects the per-request nonce while rendering, so a
 * page generated at build time has scripts with no nonce on them. With
 * 'strict-dynamic' in the policy, a browser ignores the host allowlist
 * entirely and blocks every one of those scripts: the page loads, no
 * JavaScript runs, and nothing works.
 *
 * Measured, not assumed: with the CSP in place and this line absent, the
 * homepage and the four auth pages produced 12-13 blocked scripts each
 * and never hydrated, while the already-dynamic pages had none.
 *
 * The cost is one small query per homepage view. If that ever matters,
 * cache anonymous responses at nginx rather than removing this.
 */
export const dynamic = "force-dynamic";

// The browser chrome takes the paper colour of whichever scheme is
// active, so an installed site doesn't sit under a white or black bar.
// A reader who forced a theme gets that theme's paper under both media
// queries; the toggle keeps these tags in step when the choice changes.
export async function generateViewport(): Promise<Viewport> {
  const forced = themeAttribute(await getTheme());
  return {
    themeColor: [
      { media: "(prefers-color-scheme: light)", color: THEME_COLOR[forced ?? "light"] },
      { media: "(prefers-color-scheme: dark)", color: THEME_COLOR[forced ?? "dark"] },
    ],
  };
}

export const metadata: Metadata = {
  // Without metadataBase every Open Graph and Twitter URL is emitted
  // relative, and relative URLs in a share card are simply ignored — the
  // link unfurls with no image and often no title. It is the difference
  // between a share card working and not existing.
  metadataBase: siteUrl(),

  title: {
    default: SITE_NAME,
    // Pages set only their own title; the site name is appended here so
    // it can never drift between pages.
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,

  // Generated by scripts/make-icons.mjs; the manifest (app/manifest.ts)
  // lists the larger sizes for "Add to Home Screen".
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icons/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: "/icons/apple-touch-icon.png",
  },

  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    locale: "en",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },

  alternates: {
    canonical: "/",
    // Advertises the feed to readers and to feed readers that look for it
    // in the document head, which is how most subscribe buttons work.
    types: {
      "application/rss+xml": [{ url: "/feed.xml", title: `${SITE_NAME} — latest articles` }],
    },
  },
};

/**
 * The root layout is deliberately bare. The public site, the sign-in
 * pages and the newsroom each have their own shell in a route group, so
 * the newsroom is not wearing the reader-facing masthead and footer.
 */
export default async function RootLayout({ children }: LayoutProps<"/">) {
  // Decided by src/proxy.ts from the reader's cookie or Accept-Language;
  // see src/i18n. The dictionary for that one language is handed to the
  // client provider so client components render the same text on both
  // sides of hydration.
  const locale = await getLocale();
  const { t } = await getI18n();
  // Light or dark, when the reader has chosen one (src/theme). Absent
  // means "follow the system", which the stylesheet handles on its own.
  const theme = themeAttribute(await getTheme());

  return (
    <html
      lang={locale}
      dir={LOCALE_DIR[locale]}
      data-theme={theme}
      // Tells Next.js the smooth scrolling in globals.css is deliberate,
      // so it can switch it off for the instant during a route change
      // (otherwise a navigation visibly scrolls up from the old position).
      data-scroll-behavior="smooth"
      className={`${inter.variable} ${sourceSerif.variable} ${fraunces.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-50 focus:rounded-md focus:bg-ink focus:px-4 focus:py-2 focus:text-sm focus:font-medium focus:text-paper"
        >
          {t("common.skipToContent")}
        </a>
        <I18nProvider locale={locale} messages={MESSAGES[locale]}>
          <Providers>{children}</Providers>
        </I18nProvider>
      </body>
    </html>
  );
}
