import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Newsreader } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { SITE_DESCRIPTION, SITE_NAME, siteUrl } from "@/lib/siteUrl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Headlines and article text. A serif with optical sizing, so it is
// crisp at 16px in a byline and graceful at 48px in a headline.
const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

/**
 * Every page renders per request.
 *
 * Not a performance choice — a prerequisite for the Content-Security-
 * Policy. Next.js injects the per-request nonce while rendering, so a
 * page generated at build time has scripts with no nonce on them. With
 * 'strict-dynamic' in the policy, a browser ignores the host allowlist
 * entirely and blocks every one of those scripts: the page loads, no
 * JavaScript runs, and nothing works.
 *
 * Measured, not assumed: with the CSP in place and this line absent, the
 * homepage and the four auth pages produced 12-13 blocked scripts each
 * and never hydrated, while the already-dynamic pages had none.
 *
 * The cost is one small query per homepage view. If that ever matters,
 * cache anonymous responses at nginx rather than removing this.
 */
export const dynamic = "force-dynamic";

// The browser chrome takes the paper colour of whichever scheme is
// active, so an installed site doesn't sit under a white or black bar.
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#faf8f4" },
    { media: "(prefers-color-scheme: dark)", color: "#131210" },
  ],
};

export const metadata: Metadata = {
  // Without metadataBase every Open Graph and Twitter URL is emitted
  // relative, and relative URLs in a share card are simply ignored — the
  // link unfurls with no image and often no title. It is the difference
  // between a share card working and not existing.
  metadataBase: siteUrl(),

  title: {
    default: SITE_NAME,
    // Pages set only their own title; the site name is appended here so
    // it can never drift between pages.
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,

  // Generated by scripts/make-icons.mjs; the manifest (app/manifest.ts)
  // lists the larger sizes for "Add to Home Screen".
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icons/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: "/icons/apple-touch-icon.png",
  },

  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    locale: "en",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },

  alternates: {
    canonical: "/",
    // Advertises the feed to readers and to feed readers that look for it
    // in the document head, which is how most subscribe buttons work.
    types: {
      "application/rss+xml": [{ url: "/feed.xml", title: `${SITE_NAME} — latest articles` }],
    },
  },
};

/**
 * The root layout is deliberately bare. The public site, the sign-in
 * pages and the newsroom each have their own shell in a route group, so
 * the newsroom is not wearing the reader-facing masthead and footer.
 */
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // Tells Next.js the smooth scrolling in globals.css is deliberate,
      // so it can switch it off for the instant during a route change
      // (otherwise a navigation visibly scrolls up from the old position).
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${geistMono.variable} ${newsreader.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-50 focus:rounded-md focus:bg-ink focus:px-4 focus:py-2 focus:text-sm focus:font-medium focus:text-paper"
        >
          Skip to content
        </a>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
